### ISSUE TITLE
evaluateMAP function not working 

### ISSUE THREAD

**Issue by Plovman2K** [oarriaga/paz#191]
I am trying to use the `evaluateMAP()` function with an SSD300 detector. When I do so, I get the following error:
```
Traceback (most recent call last):
  File "C:\Users\Farrukh\Documents\repos\pod-pedestrian\train_net.py", line 84, in <module>
    evaluate_model(test, model)
  File "C:\Users\Farrukh\Documents\repos\pod-pedestrian\train_net.py", line 72, in evaluate_model
    score = evaluateMAP(model, test_data, {"person": 1, "people": 2})
  File "C:\Users\Farrukh\Documents\repos\pod-pedestrian\custom_map.py", line 214, in evaluateMAP
    positives, score, match = compute_matches(
  File "C:\Users\Farrukh\Documents\repos\pod-pedestrian\custom_map.py", line 52, in compute_matches
    for box2D in results['boxes2D']:
  File "C:\Users\Farrukh\anaconda3\envs\pod-pedestrian\lib\site-packages\tensorflow\python\util\traceback_utils.py", line 153, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\Farrukh\anaconda3\envs\pod-pedestrian\lib\site-packages\tensorflow\python\ops\array_ops.py", line 899, in _check_index
    raise TypeError(_SLICE_TYPE_ERROR + ", got {!r}".format(idx))
TypeError: Only integers, slices (`:`), ellipsis (`...`), tf.newaxis (`None`) and scalar tf.int32/tf.int64 tensors are valid indices, got 'boxes2D'
```

I tried fixing this by changing `results['boxes2D']` to just `results`, which led to the following error:

```
Traceback (most recent call last):
  File "C:\Users\Farrukh\Documents\repos\pod-pedestrian\train_net.py", line 84, in <module>
    evaluate_model(test, model)
  File "C:\Users\Farrukh\Documents\repos\pod-pedestrian\train_net.py", line 72, in evaluate_model
    score = evaluateMAP(model, test_data, {"person": 1, "people": 2})
  File "C:\Users\Farrukh\Documents\repos\pod-pedestrian\custom_map.py", line 213, in evaluateMAP
    positives, score, match = compute_matches(
  File "C:\Users\Farrukh\Documents\repos\pod-pedestrian\custom_map.py", line 52, in compute_matches
    predicted_scores.append(box2D.score)
  File "C:\Users\Farrukh\anaconda3\envs\pod-pedestrian\lib\site-packages\tensorflow\python\framework\ops.py", line 513, in __getattr__
    self.__getattribute__(name)
AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'score'
```

I'm using a slightly modified version of the `compute_matches()` function (see attached) that has reshapes the image so that it can be used with the SSD300 model. The following lines are added right after the image is loaded:

```
image = resize_image(image, (300, 300))
image = np.array([image])
```

**Comment by Plovman2K** [comment]
I resolved the issue, I didn't realize you had to pass a function to `evaluateMAP` and was instead passing the model itself.

**Comment by Plovman2K** [comment]
I resolved the issue, I didn't realize you had to pass a function to `evaluateMAP` and was instead passing the model itself.
